### PR TITLE
[maint] mark developement version as "x.y.z+"

### PR DESCRIPTION
**Pull request by cbm755**
See https://savannah.gnu.org/bugs/?55829

### CODE REVIEW

**Comment by cbm755** [comment]
I've suggesting that packages indicate dev versions somewhere so users can quickly see in `pkg list`, and so that `pkg upgrade` works etc.

One approach is `0.1.0`  then `0.1.0+` during development until bumping to `0.2.0` for the next release.  Surely other valid approaches too if you don't like this one...

**Review by apjanke — APPROVED** [review]
Good idea.

**Comment by apjanke** [comment]
Merge conflict. Could you rebase?

**Comment by cbm755** [comment]
rebased

**Comment by apjanke** [comment]
Looks good. Merged!

**Pull request merged**
